#!/bin/bash
# test_dist.sh - Test distributed s-step GMRES
# 分布式 s-step GMRES 测试脚本

set -e

echo "=============================================="
echo "Distributed s-step GMRES Tests"
echo "=============================================="

# Compile
echo "Compiling..."
mpicxx -std=c++11 -O3 -framework Accelerate -o sstep_gmres_dist sstep_gmres_dist.cpp

echo ""
echo "=============================================="
echo "参数说明"
echo "=============================================="
echo ""
echo "用法: ./sstep_gmres_dist <n_global> <s> <m> <type> [tol]"
echo ""
echo "参数 | 含义            | 建议值          | 说明"
echo "-----|----------------|----------------|------------------"
echo " n   | 全局矩阵维度     | 完全平方数       | n = nx × nx, nx 为网格边长"
echo " s   | s-step 参数     | 2-3 (推荐3)     | 每块生成 s 个 Krylov 向量"
echo " m   | 最大块数        | 10-100         | 总 Krylov 维度 = s × m"
echo "type | 矩阵类型        | 0 或 1         | 0=五对角, 1=各向异性(eps=0.01)"
echo "tol  | 收敛容忍度      | 1e-6 ~ 1e-10   | 默认 1e-8 (工程标准)"
echo ""
echo "----------------------------------------------"
echo "s 参数选择:"
echo "  s=2: 最稳定, W矩阵条件数≈7, 适合极端困难问题"
echo "  s=3: 平衡选择, W矩阵条件数≈16, 论文推荐 (默认)"
echo "  s>3: 可能数值不稳定, 不推荐"
echo ""
echo "m 参数选择:"
echo "  m 决定重启前的 Krylov 子空间大小"
echo "  简单问题: m=10-20 即可收敛"
echo "  困难问题: m=30-50 或需要重启"
echo ""
echo "----------------------------------------------"
echo "测试规模对照表:"
echo ""
echo "| n       | nx  | 网格规模 | 问题难度 |"
echo "|---------|-----|---------|---------|"
echo "| 400     | 20  | 小      | 简单    |"
echo "| 10000   | 100 | 中      | 中等    |"
echo "| 100000  | 316 | 大      | 较难    |"
echo "| 1000000 | 1000| 超大    | 困难    |"
echo ""
echo "=============================================="
echo ""

echo "=== Phase 1: Single process validation ==="
echo "命令: mpirun -np 1 ./sstep_gmres_dist 400 3 15 0 1e-8"
echo "  n=400   : 20×20 网格"
echo "  s=3     : 每块3个Krylov向量"
echo "  m=15    : 最多15块 (Krylov维度=45)"
echo "  type=0  : 五对角矩阵"
echo "  tol=1e-8: 收敛标准"
echo ""
mpirun -np 1 ./sstep_gmres_dist 400 3 15 0 1e-8

echo ""
echo "=== Phase 2: Multi-process correctness ==="
echo "命令: mpirun -np 4 ./sstep_gmres_dist 400 3 15 0 1e-8"
echo "  np=4    : 4个MPI进程"
echo "  每进程处理 400/4=100 行"
echo ""
mpirun -np 4 ./sstep_gmres_dist 400 3 15 0 1e-8

echo ""
echo "=== Phase 3: Large-scale performance ==="
echo "命令: mpirun -np 10 ./sstep_gmres_dist 100000 3 30 0 1e-8"
echo "  n=100000: 316×316 网格"
echo "  m=30    : 最多30块 (Krylov维度=90)"
echo "  np=10   : 10个进程, 每进程10000行"
echo ""
mpirun -np 10 ./sstep_gmres_dist 100000 3 30 0 1e-8

echo ""
echo "=== Phase 4: Restart functionality ==="
echo "测试 1: 五对角矩阵 (快速收敛)"
echo "命令: mpirun -np 4 ./sstep_gmres_dist 10000 3 10 0 1e-8 25"
echo "  max_restarts=25: 允许多次重启"
echo ""
mpirun -np 4 ./sstep_gmres_dist 10000 3 10 0 1e-8 25

echo ""
echo "测试 2: max_restarts=1 (等价于无重启)"
echo "命令: mpirun -np 4 ./sstep_gmres_dist 10000 3 10 0 1e-8 1"
echo "  max_restarts=1: 仅一轮, 与原版本行为一致"
echo ""
mpirun -np 4 ./sstep_gmres_dist 10000 3 10 0 1e-8 1

echo ""
echo "=============================================="
echo "Tests complete!"
echo "=============================================="
echo ""
echo "手动测试示例:"
echo ""
echo "# 小规模快速验证"
echo "mpirun -np 1 ./sstep_gmres_dist 100 3 10 0 1e-8"
echo ""
echo "# 中等规模"
echo "mpirun -np 4 ./sstep_gmres_dist 10000 3 20 0 1e-8"
echo ""
echo "# 大规模 (推荐 np=2-4)"
echo "mpirun -np 4 ./sstep_gmres_dist 1000000 3 50 0 1e-4"
echo ""
echo "# 各向异性矩阵 (更难收敛, 需要重启)"
echo "mpirun -np 4 ./sstep_gmres_dist 10000 3 30 1 1e-6 25"