//****************************************************************************\
//*                    National Numerical Windtunnel                          *
//*         FlowStar -- Flow Simulation Tools for Aerospace Research          *
//*                  Computational Aerodynamics Institute                     *
//*              China Aerodynamics Research&Development Center               *
//*                       Mianyang, Sichuan, China                            *
//****************************************************************************/
///
/// \file   io_grid.h
/// \brief  functions for grid output
/// \author tangj, zhangyb, leebin, zhengming
/// \date   2020-01-12
/// \copyright  C.All rights reserved. 2020-2020, CAI/CARDC
/// 
/// \par    Update records:
/// <pre>
/// Date        Author     Description
/// 
/// </pre>

#ifndef MFL_IO_GRID_H
#define MFL_IO_GRID_H

#include "grid_polyhedra.h"

#include <string>
#include <vector>

namespace mflow
{

namespace GridIO
{
using std::string;
using std::vector;


// Additional grid information returned.
// Those information may be used by other objects, such as zone.  
struct ExtraGridData
{
    typedef vector<string> BCNamesType;

    // save names of boundary patch
    BCNamesType bc_patch_names;
};

// Read CGNS grid
void ReadCGNSGrid(PolyGrid *grid, const string &filename, ExtraGridData &extra_grid_data);
// Read grid of MFlow binary format generated by MFlow preprocessing.
// Each data of parallel grid saved in one file, the filename is different for different processor.
void ReadMFlowGrid_binary(PolyGrid **grids, const IntType mg, const string &filename, ExtraGridData &extra_grid_data);

} // ~namespace GridIO

} // ~namespace mflow

#endif  //~MFL_IO_GRID_H
